Updated dependency update patch file

diff --git a/dependency-updates.patch b/dependency-updates.patch
--- a/dependency-updates.patch
+++ b/dependency-updates.patch
@@ -1,18 +1,17 @@
 diff --git a/build.gradle b/build.gradle
-index 79bd47d..68763ee 100644
+index 3904219..7fc9667 100644
 --- a/build.gradle
 +++ b/build.gradle
 @@ -1,7 +1,7 @@
  plugins {
  	id 'java'
+ 	id 'jacoco'
 -	id 'org.springframework.boot' version '3.1.2'
--	id 'io.spring.dependency-management' version '1.1.2'
 +	id 'org.springframework.boot' version '3.4.4'
-+	id 'io.spring.dependency-management' version '1.1.7'
+ 	id 'io.spring.dependency-management' version '1.1.2'
+ 	id "nebula.dependency-lock" version "12.7.1"
  }
- 
- group = 'com.shelter'
-@@ -16,7 +16,7 @@ repositories {
+@@ -18,7 +18,7 @@ repositories {
  }
  
  dependencies {
@@ -21,91 +20,266 @@ index 79bd47d..68763ee 100644
  
  	implementation 'org.springframework.boot:spring-boot-starter-web'
  	implementation 'org.springframework.boot:spring-boot-starter-webflux'
+diff --git a/dependency-updates.patch b/dependency-updates.patch
+index a7f6347..e69de29 100644
+--- a/dependency-updates.patch
++++ b/dependency-updates.patch
+@@ -1,116 +0,0 @@
+-diff --git a/build.gradle b/build.gradle
+-index 79bd47d..68763ee 100644
+---- a/build.gradle
+-+++ b/build.gradle
+-@@ -1,7 +1,7 @@
+- plugins {
+- 	id 'java'
+--	id 'org.springframework.boot' version '3.1.2'
+--	id 'io.spring.dependency-management' version '1.1.2'
+-+	id 'org.springframework.boot' version '3.4.4'
+-+	id 'io.spring.dependency-management' version '1.1.7'
+- }
+- 
+- group = 'com.shelter'
+-@@ -16,7 +16,7 @@ repositories {
+- }
+- 
+- dependencies {
+--	implementation 'com.launchdarkly:launchdarkly-java-server-sdk:6.2.1'
+-+	implementation 'com.launchdarkly:launchdarkly-java-server-sdk:7.7.0'
+- 
+- 	implementation 'org.springframework.boot:spring-boot-starter-web'
+- 	implementation 'org.springframework.boot:spring-boot-starter-webflux'
+-diff --git a/gradle/wrapper/gradle-wrapper.properties b/gradle/wrapper/gradle-wrapper.properties
+-index 5c6f89d..c6f0030 100644
+---- a/gradle/wrapper/gradle-wrapper.properties
+-+++ b/gradle/wrapper/gradle-wrapper.properties
+-@@ -1,7 +1,6 @@
+- distributionBase=GRADLE_USER_HOME
+- distributionPath=wrapper/dists
+--distributionUrl=https\://services.gradle.org/distributions/gradle-7.6.1-bin.zip
+-+distributionUrl=https\://services.gradle.org/distributions/gradle-8.13-bin.zip
+- networkTimeout=10000
+--validateDistributionUrl=true
+- zipStoreBase=GRADLE_USER_HOME
+- zipStorePath=wrapper/dists
+-diff --git a/gradlew b/gradlew
+-index fcb6fca..65dcd68 100755
+---- a/gradlew
+-+++ b/gradlew
+-@@ -85,6 +85,9 @@ done
+- APP_BASE_NAME=${0##*/}
+- APP_HOME=$( cd "${APP_HOME:-./}" && pwd -P ) || exit
+- 
+-+# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
+-+DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'
+-+
+- # Use the maximum available, or set MAX_FD != -1 to use that value.
+- MAX_FD=maximum
+- 
+-@@ -130,13 +133,10 @@ location of your Java installation."
+-     fi
+- else
+-     JAVACMD=java
+--    if ! command -v java >/dev/null 2>&1
+--    then
+--        die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.
+-+    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.
+- 
+- Please set the JAVA_HOME variable in your environment to match the
+- location of your Java installation."
+--    fi
+- fi
+- 
+- # Increase the maximum file descriptors if we can.
+-@@ -144,7 +144,7 @@ if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
+-     case $MAX_FD in #(
+-       max*)
+-         # In POSIX sh, ulimit -H is undefined. That's why the result is checked to see if it worked.
+--        # shellcheck disable=SC3045
+-+        # shellcheck disable=SC3045 
+-         MAX_FD=$( ulimit -H -n ) ||
+-             warn "Could not query maximum file descriptor limit"
+-     esac
+-@@ -152,7 +152,7 @@ if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
+-       '' | soft) :;; #(
+-       *)
+-         # In POSIX sh, ulimit -n is undefined. That's why the result is checked to see if it worked.
+--        # shellcheck disable=SC3045
+-+        # shellcheck disable=SC3045 
+-         ulimit -n "$MAX_FD" ||
+-             warn "Could not set maximum file descriptor limit to $MAX_FD"
+-     esac
+-@@ -197,10 +197,6 @@ if "$cygwin" || "$msys" ; then
+-     done
+- fi
+- 
+--
+--# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
+--DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'
+--
+- # Collect all arguments for the java command;
+- #   * $DEFAULT_JVM_OPTS, $JAVA_OPTS, and $GRADLE_OPTS can contain fragments of
+- #     shell script including quotes and variable substitutions, so put them in
+-diff --git a/src/test/java/com/shelter/launchdarklyshelterdemo/DemoApplicationTests.java b/src/test/java/com/shelter/launchdarklyshelterdemo/DemoApplicationTests.java
+-index dfd8190..6f04fc7 100644
+---- a/src/test/java/com/shelter/launchdarklyshelterdemo/DemoApplicationTests.java
+-+++ b/src/test/java/com/shelter/launchdarklyshelterdemo/DemoApplicationTests.java
+-@@ -7,7 +7,7 @@ import org.mockito.Mockito;
+- import org.springframework.beans.factory.annotation.Autowired;
+- import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
+- import org.springframework.boot.test.context.SpringBootTest;
+--import org.springframework.boot.test.mock.mockito.MockBean;
+-+import org.springframework.test.context.bean.override.mockito.MockitoBean;
+- import org.springframework.test.web.servlet.MockMvc;
+- 
+- import java.util.List;
+-@@ -22,7 +22,7 @@ class DemoApplicationTests {
+- 	@Autowired
+- 	MockMvc mockMvc;
+- 
+--	@MockBean
+-+	@MockitoBean
+- 	FakePolicyService policyService;
+- 
+- 	@Test
 diff --git a/gradle/wrapper/gradle-wrapper.properties b/gradle/wrapper/gradle-wrapper.properties
-index 5c6f89d..c6f0030 100644
+index 5c6f89d..37f853b 100644
 --- a/gradle/wrapper/gradle-wrapper.properties
 +++ b/gradle/wrapper/gradle-wrapper.properties
-@@ -1,7 +1,6 @@
+@@ -1,6 +1,6 @@
  distributionBase=GRADLE_USER_HOME
  distributionPath=wrapper/dists
 -distributionUrl=https\://services.gradle.org/distributions/gradle-7.6.1-bin.zip
 +distributionUrl=https\://services.gradle.org/distributions/gradle-8.13-bin.zip
  networkTimeout=10000
--validateDistributionUrl=true
+ validateDistributionUrl=true
  zipStoreBase=GRADLE_USER_HOME
- zipStorePath=wrapper/dists
 diff --git a/gradlew b/gradlew
-index fcb6fca..65dcd68 100755
+index fcb6fca..faf9300 100755
 --- a/gradlew
 +++ b/gradlew
-@@ -85,6 +85,9 @@ done
- APP_BASE_NAME=${0##*/}
- APP_HOME=$( cd "${APP_HOME:-./}" && pwd -P ) || exit
+@@ -15,6 +15,8 @@
+ # See the License for the specific language governing permissions and
+ # limitations under the License.
+ #
++# SPDX-License-Identifier: Apache-2.0
++#
  
-+# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
-+DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'
-+
+ ##############################################################################
+ #
+@@ -55,7 +57,7 @@
+ #       Darwin, MinGW, and NonStop.
+ #
+ #   (3) This script is generated from the Groovy template
+-#       https://github.com/gradle/gradle/blob/HEAD/subprojects/plugins/src/main/resources/org/gradle/api/internal/plugins/unixStartScript.txt
++#       https://github.com/gradle/gradle/blob/HEAD/platforms/jvm/plugins-application/src/main/resources/org/gradle/api/internal/plugins/unixStartScript.txt
+ #       within the Gradle project.
+ #
+ #       You can find Gradle at https://github.com/gradle/gradle/.
+@@ -83,7 +85,8 @@ done
+ # This is normally unused
+ # shellcheck disable=SC2034
+ APP_BASE_NAME=${0##*/}
+-APP_HOME=$( cd "${APP_HOME:-./}" && pwd -P ) || exit
++# Discard cd standard output in case $CDPATH is set (https://github.com/gradle/gradle/issues/25036)
++APP_HOME=$( cd -P "${APP_HOME:-./}" > /dev/null && printf '%s\n' "$PWD" ) || exit
+ 
  # Use the maximum available, or set MAX_FD != -1 to use that value.
  MAX_FD=maximum
- 
-@@ -130,13 +133,10 @@ location of your Java installation."
-     fi
- else
-     JAVACMD=java
--    if ! command -v java >/dev/null 2>&1
--    then
--        die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.
-+    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.
- 
- Please set the JAVA_HOME variable in your environment to match the
- location of your Java installation."
--    fi
- fi
- 
- # Increase the maximum file descriptors if we can.
-@@ -144,7 +144,7 @@ if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
+@@ -144,7 +147,7 @@ if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
      case $MAX_FD in #(
        max*)
          # In POSIX sh, ulimit -H is undefined. That's why the result is checked to see if it worked.
 -        # shellcheck disable=SC3045
-+        # shellcheck disable=SC3045 
++        # shellcheck disable=SC2039,SC3045
          MAX_FD=$( ulimit -H -n ) ||
              warn "Could not query maximum file descriptor limit"
      esac
-@@ -152,7 +152,7 @@ if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
+@@ -152,7 +155,7 @@ if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
        '' | soft) :;; #(
        *)
          # In POSIX sh, ulimit -n is undefined. That's why the result is checked to see if it worked.
 -        # shellcheck disable=SC3045
-+        # shellcheck disable=SC3045 
++        # shellcheck disable=SC2039,SC3045
          ulimit -n "$MAX_FD" ||
              warn "Could not set maximum file descriptor limit to $MAX_FD"
      esac
-@@ -197,10 +197,6 @@ if "$cygwin" || "$msys" ; then
-     done
- fi
+@@ -201,11 +204,11 @@ fi
+ # Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
+ DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'
  
--
--# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
--DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'
--
- # Collect all arguments for the java command;
- #   * $DEFAULT_JVM_OPTS, $JAVA_OPTS, and $GRADLE_OPTS can contain fragments of
- #     shell script including quotes and variable substitutions, so put them in
+-# Collect all arguments for the java command;
+-#   * $DEFAULT_JVM_OPTS, $JAVA_OPTS, and $GRADLE_OPTS can contain fragments of
+-#     shell script including quotes and variable substitutions, so put them in
+-#     double quotes to make sure that they get re-expanded; and
+-#   * put everything else in single quotes, so that it's not re-expanded.
++# Collect all arguments for the java command:
++#   * DEFAULT_JVM_OPTS, JAVA_OPTS, and optsEnvironmentVar are not allowed to contain shell fragments,
++#     and any embedded shellness will be escaped.
++#   * For example: A user cannot expect ${Hostname} to be expanded, as it is an environment variable and will be
++#     treated as '${Hostname}' itself on the command line.
+ 
+ set -- \
+         "-Dorg.gradle.appname=$APP_BASE_NAME" \
+diff --git a/gradlew.bat b/gradlew.bat
+index 93e3f59..9d21a21 100644
+--- a/gradlew.bat
++++ b/gradlew.bat
+@@ -13,6 +13,8 @@
+ @rem See the License for the specific language governing permissions and
+ @rem limitations under the License.
+ @rem
++@rem SPDX-License-Identifier: Apache-2.0
++@rem
+ 
+ @if "%DEBUG%"=="" @echo off
+ @rem ##########################################################################
+@@ -43,11 +45,11 @@ set JAVA_EXE=java.exe
+ %JAVA_EXE% -version >NUL 2>&1
+ if %ERRORLEVEL% equ 0 goto execute
+ 
+-echo.
+-echo ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.
+-echo.
+-echo Please set the JAVA_HOME variable in your environment to match the
+-echo location of your Java installation.
++echo. 1>&2
++echo ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH. 1>&2
++echo. 1>&2
++echo Please set the JAVA_HOME variable in your environment to match the 1>&2
++echo location of your Java installation. 1>&2
+ 
+ goto fail
+ 
+@@ -57,11 +59,11 @@ set JAVA_EXE=%JAVA_HOME%/bin/java.exe
+ 
+ if exist "%JAVA_EXE%" goto execute
+ 
+-echo.
+-echo ERROR: JAVA_HOME is set to an invalid directory: %JAVA_HOME%
+-echo.
+-echo Please set the JAVA_HOME variable in your environment to match the
+-echo location of your Java installation.
++echo. 1>&2
++echo ERROR: JAVA_HOME is set to an invalid directory: %JAVA_HOME% 1>&2
++echo. 1>&2
++echo Please set the JAVA_HOME variable in your environment to match the 1>&2
++echo location of your Java installation. 1>&2
+ 
+ goto fail
+ 
 diff --git a/src/test/java/com/shelter/launchdarklyshelterdemo/DemoApplicationTests.java b/src/test/java/com/shelter/launchdarklyshelterdemo/DemoApplicationTests.java
-index dfd8190..6f04fc7 100644
+index dfd8190..d8f8412 100644
 --- a/src/test/java/com/shelter/launchdarklyshelterdemo/DemoApplicationTests.java
 +++ b/src/test/java/com/shelter/launchdarklyshelterdemo/DemoApplicationTests.java
-@@ -7,7 +7,7 @@ import org.mockito.Mockito;
+@@ -7,7 +7,6 @@ import org.mockito.Mockito;
  import org.springframework.beans.factory.annotation.Autowired;
  import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
  import org.springframework.boot.test.context.SpringBootTest;
 -import org.springframework.boot.test.mock.mockito.MockBean;
-+import org.springframework.test.context.bean.override.mockito.MockitoBean;
  import org.springframework.test.web.servlet.MockMvc;
  
  import java.util.List;
-@@ -22,7 +22,7 @@ class DemoApplicationTests {
+@@ -22,7 +21,7 @@ class DemoApplicationTests {
  	@Autowired
  	MockMvc mockMvc;
  
